version: "3"
services:
  app:
    image: suecharo/sapporo-service:1.0.5
    container_name: sapporo
    volumes:
      - ${PWD}:/app
      # The ones below are mounted for cwltool and DinD.
      - ${PWD}/run:${PWD}/run
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      # Priority: [Command Line Argument] -> [Environment Variable] -> [Default Values]
      - SAPPORO_HOST=0.0.0.0
      - SAPPORO_PORT=1122
      - SAPPORO_DEBUG=False
      - SAPPORO_RUN_DIR=${PWD}/run
      # - SAPPORO_GET_RUNS=True
      # - SAPPORO_RUN_ONLY_REGISTERED_WORKFLOWS=False
      # - SAPPORO_ACCESS_CONTROL_ALLOW_ORIGIN=*
      # - SAPPORO_URL_PREFIX=/
    ports:
      - 0.0.0.0:1122:1122
    restart: on-failure
    working_dir: /app
    command: ["sapporo"]
    networks:
      - sapporo

networks:
  sapporo:
    external:
      name: sapporo-network
