version: "3"
services:
  app:
    image: suecharo/sapporo-service:1.0.2
    container_name: sapporo
    volumes:
      - /tmp:/tmp
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:${PWD}
    environment:
      - SAPPORO_HOST=0.0.0.0
      - SAPPORO_PORT=8080
      - SAPPORO_DEBUG=False
      - SAPPORO_RUN_DIR=${PWD}/run
      - SAPPORO_GET_RUNS=True
      - SAPPORO_RUN_ONLY_REGISTERED_WORKFLOWS=False
      - SAPPORO_ACCESS_CONTROL_ALLOW_ORIGIN=*
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["sapporo"]
