version: "3"
services:
  app:
    image: suecharo/sapporo-service:v0.4.1
    container_name: sapporo-service-app
    restart: always
    volumes:
      - /tmp:/tmp
      - /usr/bin/docker:/usr/bin/docker
      - /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/etc/uwsgi:/opt/SAPPORO/SAPPORO-service/etc/uwsgi
      - ${PWD}/log/app:/opt/SAPPORO/SAPPORO-service/log/app
      - ${PWD}/run:/opt/SAPPORO/SAPPORO-service/run
      - ${PWD}/run/cache:/.cache
      - ${PWD}/service-info.yml:/opt/SAPPORO/SAPPORO-service/service-info.yml
      - ${PWD}/src:/opt/SAPPORO/SAPPORO-service/src
      - ${PWD}/workflow-info.yml:/opt/SAPPORO/SAPPORO-service/workflow-info.yml
    environment:
      - DEBUG=${SAPPORO_SERVICE_DEBUG:-False} # Flask debug mode
      - GET_RUNS=${SAPPORO_SERVICE_GET_RUNS:-True}
      - TOKEN_AUTH=${SAPPORO_SERVICE_TOKEN_AUTH:-False}
      - LOG_LEVEL=${SAPPORO_SERVICE_LOG_LEVEL:-INFO} # DEBUG or INFO
    user: ${UID:-0}:${DOCKER_GID:-999} # Docker group
    command: ["uwsgi", "/opt/SAPPORO/SAPPORO-service/etc/uwsgi/uwsgi.ini"]
    networks:
      - sapporo
  web:
    image: nginx:1.16.0-alpine
    container_name: sapporo-service-web
    restart: always
    volumes:
      - ${PWD}/etc/nginx/cache:/var/cache/nginx
      - ${PWD}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/etc/nginx/run:/var/run/nginx
      - ${PWD}/etc/uwsgi:/etc/nginx/uwsgi
      - ${PWD}/log/nginx:/var/log/nginx
    user: ${UID:-0}:${GID:-0}
    networks:
      - sapporo
    ports:
      - ${SAPPORO_SERVICE_PORT:-1122}:8080
    depends_on:
      - app

networks:
  sapporo:
    external:
      name: sapporo-network
