name: upload_pypi

on:
  release:
    types:
      - published
  workflow_dispatch: {}

jobs:
  upload_pypi:
    if: github.repository == 'ddbj/SAPPORO-service'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python3 -m pip install --no-cache-dir --progress-bar off -U pip setuptools wheel
          python3 -m pip install twine
      - name: Build a tar ball
        run: |
          python3 setup.py sdist
          python3 setup.py bdist_wheel
      - name: Verify the distributions
        run: twine check dist/*
      - name: Publish distribution to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
